spring.application.name=investir_mais

spring.mvc.problemdetails.enabled=true

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS:true}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/investir_mais}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.enable-data-rest=true
springdoc.enable-spring-data-rest=true

spring.h2.console.enabled=${H2_CONSOLE_ENABLED:false}
spring.h2.console.path=/h2-console

app.public-base-url=${APP_PUBLIC_BASE_URL:http://localhost:8080}

brapi.token=${BRAPI_TOKEN:}

spring.cache.type=caffeine
spring.cache.cache-names=revokedTokens
spring.cache.caffeine.spec=expireAfterWrite=1d,maximumSize=10000

spring.threads.virtual.enabled=true