spring.application.name=investir_mais

# --- Configurações de E-mail ---
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS:true}

# --- Configurações de Banco de Dados ---
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/investir_mais}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Swagger / OpenAPI ---
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.enable-data-rest=true
springdoc.enable-spring-data-rest=true

# --- Console Web do H2 (para testes em memória) ---
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:false}
spring.h2.console.path=/h2-console

# --- Configurações da Aplicação ---
app.public-base-url=${APP_PUBLIC_BASE_URL:http://localhost:8080}